circuit_info:
  r_ser: 7.5
  r_main: 68
  c_main: 220.0e-6
  l_main: 8.2e-3
  l_main_r: 0.6
  r_ramp1: 12
  l_ramp1: 0.62e-3
  l_ramp1_r: 0.5
  r_ramp2: 68
  l_ramp2: 0.33e-3
  l_ramp2_r: 0.3
drv_info:
  p_drv: 100
  r_drv: 8
  r_amp: 8
meas_config:
  path: ../../Measurement/fatcab_impedance.txt